version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: /data/postgres
      APP_DB_NAME: notesDb

    volumes:
      - postgres:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped

volumes:
  postgres: