server:
  port: 8080
  error:
    include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/notesDb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver